Add support for checking mandatory weakreferences missing
Jahia/content-integrity pull request #2
Opened 2017-02-27 13:03 UTC by jordannroussel

2017-03-15 09:37 UTC, dsaulnier requested changes

2017-03-15 09:37 UTC, dsaulnier commented on src/main/java/org/jahia/modules/verifyintegrity/services/VerifyIntegrityService.java
> +										.getNode();
If the property exists but the reference is broken, .getNode() throws a javax.jcr.ItemNotFoundException

2017-03-24 09:39 UTC, jordannroussel commented on src/main/java/org/jahia/modules/verifyintegrity/services/VerifyIntegrityService.java
> +										.getNode();
Added a new catch for such case.

2017-03-27 09:34 UTC, dsaulnier approved these changes

2017-03-27 11:57 UTC, merged